trigger:
  branches:
    exclude:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Default'

jobs:
- job: CI
  displayName: 'Basic CI'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      echo "Basic CI Pipeline"
    displayName: 'Script running'

  - script: |
      python -m venv venv
      source venv\Scripts\activate
      pip install flake8
      flake8 --max-line-length=100
    displayName: 'Setup and Code linting with Flake8'

  - script: |
      pytest --cov=.
    displayName: 'Run Unit Tests and Generate Coverage Report'


- job: Release
  displayName: "Release Pipeline"
  dependsOn: CI
  condition: succeeded()
  steps:
    - script: echo "Basic Release Pipeline"
      displayName: "Release"